In [8]:
import torch

In [3]:
a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [4]:
b = torch.tensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [5]:
print(a.shape, b.shape)

torch.Size([3]) torch.Size([4, 3])


In [7]:
print(b.view(-1, 2))

tensor([[2, 1],
        [4, 3],
        [5, 4],
        [1, 2],
        [0, 4],
        [3, 2]])


In [9]:
print(b[:, 1])

tensor([1, 5, 2, 3])


In [ ]:
# Move to GPU - x.cuda()


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=49da15f7-246c-45df-bc8f-6f9233c2b1e1' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>